import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from 'react-hot-toast';


import Sidebar from "./sidebar/page";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <div className="flex min-h-screen">
            {/* Sidebar on the left */}
            <Sidebar />
  
            {/* Main content on the right */}
            <main className="flex-1">{children}</main>
          
          </div>
          <Toaster 
    position="top-center"
    reverseOrder={false}
    toastOptions={{
      duration: 2000,
      style: { background: '#333', color: '#fff' },
    }}
  />
        </body>
      </html>
    );
  }
  
